Repository vapor/mysql-nio, pull requests merged in 2020-07, with the labels that each got.

#35 Fix decimal handling for MySQLData
  Sources/MySQLNIO/MySQLData.swift
  Sources/MySQLNIO/MySQLDataConvertible.swift
  Tests/MySQLNIOTests/MySQLNIOTests.swift
Labels: bug, enhancement, semver-minor

#40 Improve CI
  .github/workflows/test.yml
  Sources/MySQLNIO/MySQLData.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+DataType.swift
  Tests/MySQLNIOTests/MySQLNIOTests.swift
  docker-compose.yml
Labels: enhancement, semver-patch

#41 Add server version check
  Sources/MySQLNIO/MySQLConnectionHandler.swift
  docker-compose.yml
Labels: bug, semver-patch

#48 Add query timeout tests
  Tests/MySQLNIOTests/MySQLNIOTests.swift
Labels: bug

#50 MYSQL_TIME improvements
  Sources/MySQLNIO/MySQLData.swift
  Sources/MySQLNIO/MySQLTime.swift
  Tests/MySQLNIOTests/MySQLNIOTests.swift
Labels: enhancement, semver-minor

#52 Docs + missing functionality
  .github/contributing.md
  README.md
  Sources/MySQLNIO/MySQLConnection.swift
  Sources/MySQLNIO/MySQLConnectionHandler.swift
  Sources/MySQLNIO/MySQLData.swift
Labels: enhancement, semver-minor

#54 Fix MYSQL_TIME data type
  Sources/MySQLNIO/MySQLData.swift
  Sources/MySQLNIO/MySQLTime.swift
  Tests/MySQLNIOTests/MySQLNIOTests.swift
Labels: bug, semver-patch

#53 Major fixes to authentication support
  Sources/MySQLNIO/MySQLConnectionHandler.swift
  Sources/MySQLNIO/MySQLError.swift
  Sources/MySQLNIO/MySQLTime.swift
  Sources/MySQLNIO/Packet/MySQLPacket.swift
  Sources/MySQLNIO/Utilities/CryptoUtils.swift
  Tests/MySQLNIOTests/MySQLNIOTests.swift
  Tests/MySQLNIOTests/Utilities.swift
Labels: bug, enhancement, semver-minor
