Repository vapor/mysql-nio, pull requests merged in 2020-05, with the labels that each got.

#26 Decode string from tiny, medium and long blob
  Sources/MySQLNIO/MySQLData.swift
Labels: bug, enhancement, semver-patch

#27 Rmann/fix constraint error
  Sources/MySQLNIO/MySQLError.swift
  Sources/MySQLNIO/MySQLQueryCommand.swift
  Tests/MySQLNIOTests/NIOMySQLTests.swift
Labels: bug, semver-major

#28 Copy row byte buffer slices
  Sources/MySQLNIO/Protocol/MySQLProtocol+BinaryResultSetRow.swift
Labels: bug, semver-patch

#29 MySQL driver no longer crashes on auth failures
  Sources/MySQLNIO/MySQLConnection.swift
Labels: bug, semver-patch
