Repository vapor/mysql-nio, pull requests merged in 2023-05, with the labels that each got.

#94 Add missing LICENSE file
  LICENSE
Labels: no-release-needed

#95 Several very long overdue crash fixes
  .dockerignore
  .github/workflows/projectboard.yml
  .github/workflows/test.yml
  README.md
  Sources/MySQLNIO/Exports.swift
  Sources/MySQLNIO/MySQLConnection.swift
  Sources/MySQLNIO/MySQLConnectionHandler.swift
  Sources/MySQLNIO/MySQLDatabase.swift
  Sources/MySQLNIO/MySQLQueryCommand.swift
  Sources/MySQLNIO/MySQLSimpleQueryCommand.swift
  Sources/MySQLNIO/MySQLTime.swift
  Sources/MySQLNIO/Packet/MySQLPacket.swift
  Sources/MySQLNIO/Packet/MySQLPacketDecoder.swift
  Sources/MySQLNIO/Packet/MySQLPacketEncoder.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+BinaryResultSetRow.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+COM_QUERY.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+COM_STMT_CLOSE.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+COM_STMT_EXECUTE.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+COM_STMT_PREPARE.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+COM_STMT_PREPARE_OK.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+CapabilityFlags.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+CharacterSet.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+ColumnDefinition41.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+ColumnFlags.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+DataType.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+ERR_Packet.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+ErrorCode.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+HandshakeResponse41.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+HandshakeV10.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+NullBitmap.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+OK_Packet.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+SSLRequest.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+StatusFlags.swift
  Sources/MySQLNIO/Protocol/MySQLProtocol+TextResultSetRow.swift
  Sources/MySQLNIO/Utilities/CryptoUtils.swift
  Tests/MySQLNIOTests/MySQLNIOTests.swift
  Tests/MySQLNIOTests/Utilities.swift
  docker-compose.yml
Labels: bug, semver-patch

#72 Parse timestamp columns in text format. Fixes vapor/mysql-nio#71
  Sources/MySQLNIO/MySQLData.swift
  Sources/MySQLNIO/MySQLTime.swift
  Tests/MySQLNIOTests/MySQLNIOTests.swift
Labels: enhancement, semver-minor
